"""
State-driven face animation for Misty II.

Provides a FaceAnimator class that maps controller states to animated
face expressions. Runs a single daemon thread that pushes frames to
Misty's display via REST at a configurable FPS.

Design: docs/design-animated-face-expressions.md §5
Phase 1 validation: tools/face_display_probe.py (max ~10 FPS, 4 FPS recommended)

Usage:
    animator = FaceAnimator(misty_base_url, enabled=True)
    animator.start()
    animator.set_state(State.IDLE)       # non-blocking
    animator.set_state(State.LISTENING)  # switches immediately
    animator.stop()                      # bounded join
"""

import logging
import threading
import time
from dataclasses import dataclass
from enum import Enum
from typing import Optional

import requests

logger = logging.getLogger(__name__)


# Re-declare State locally to avoid circular import with misty_controller.
# The animator accepts any enum with matching .value strings.
class AnimationState(Enum):
    """Animation states that map to controller states."""
    DISCONNECTED = "DISCONNECTED"
    IDLE = "IDLE"
    RECORDING = "RECORDING"
    PROCESSING = "PROCESSING"
    PLAYING = "PLAYING"
    LISTENING = "LISTENING"
    MOVING = "MOVING"
    REARMING = "REARMING"
    REBOOTING = "REBOOTING"
    CHARGING = "CHARGING"
    ERROR = "ERROR"


@dataclass(frozen=True)
class AnimationSpec:
    """Defines how a state's face animation behaves.

    Attributes:
        frames: Ordered tuple of Misty image filenames. Length >= 1.
        fps: Target frames per second (clamped to max_fps at runtime).
        loop: If True, loop frames continuously. If False, play once and hold last.
        static_fallback: Single image used when animation is disabled or fails.
    """
    frames: tuple
    fps: float = 1.0
    loop: bool = True
    static_fallback: str = ""

    @property
    def is_single_frame(self) -> bool:
        return len(self.frames) <= 1


# Default animation specs — custom face assets with firmware-native GIF looping.
# GIFs loop on-device with zero REST traffic. Single-frame specs suffice because
# the firmware handles animation internally once the GIF is displayed.
DEFAULT_ANIMATION_MAP: dict[str, AnimationSpec] = {
    "DISCONNECTED": AnimationSpec(
        frames=("face_talking_sad.gif",),
        static_fallback="face_talking_sad.gif",
    ),
    "IDLE": AnimationSpec(
        # Custom idle GIF — blink + eye shift, firmware loops natively
        frames=("face_idle.gif",),
        static_fallback="face_idle.gif",
    ),
    "RECORDING": AnimationSpec(
        # Attentive listening face — wide eyes, slightly open mouth
        frames=("face_listening.png",),
        static_fallback="face_listening.png",
    ),
    "PROCESSING": AnimationSpec(
        # Thinking eyes GIF — eyes shift side to side
        frames=("face_processing.gif",),
        static_fallback="face_processing.gif",
    ),
    "PLAYING": AnimationSpec(
        # Talking — default neutral, controller can override with emotion variant
        frames=("face_talking_neutral.gif",),
        static_fallback="face_talking_neutral.gif",
    ),
    "LISTENING": AnimationSpec(
        # Follow-up listening — same attentive face
        frames=("face_listening.png",),
        static_fallback="face_listening.png",
    ),
    "MOVING": AnimationSpec(
        frames=("face_talking_excited.gif",),
        static_fallback="face_talking_excited.gif",
    ),
    "REARMING": AnimationSpec(
        frames=("face_idle.gif",),
        static_fallback="face_idle.gif",
    ),
    "REBOOTING": AnimationSpec(
        # Sad face during reboot — she's going to sleep
        frames=("face_talking_sad.gif",),
        static_fallback="face_talking_sad.gif",
    ),
    "CHARGING": AnimationSpec(
        # Idle face while charging
        frames=("face_idle.gif",),
        static_fallback="face_idle.gif",
    ),
    "ERROR": AnimationSpec(
        frames=("face_talking_sad.gif",),
        static_fallback="face_talking_sad.gif",
    ),
}


# Emotion variants the custom face system supports. These map 1:1 to the
# face_talking_{emotion}.gif assets generated by tools/generate_face_assets.py.
VALID_EMOTIONS: frozenset = frozenset(
    {"neutral", "happy", "excited", "sad", "curious"}
)
DEFAULT_EMOTION = "neutral"

# States whose displayed frame is driven by the current emotion rather than a
# fixed spec. For these, the animator selects face_talking_{emotion}.gif so the
# talking mouth animates with an emotion-appropriate base face.
EMOTION_TALKING_STATES: frozenset = frozenset({"PLAYING"})


def talking_face_for_emotion(emotion: str) -> str:
    """Return the custom talking-face GIF filename for an emotion.

    Falls back to the neutral variant for unknown/empty emotions so callers
    never produce an invalid filename.
    """
    e = (emotion or "").strip().lower()
    if e not in VALID_EMOTIONS:
        e = DEFAULT_EMOTION
    return f"face_talking_{e}.gif"


# Built-in Misty firmware faces used as a fallback when the custom face assets
# are not available on the device (e.g., upload failed or assets missing).
# These ship with every Misty II, so displaying them never fails for a missing
# file. Keyed by animation state.
BUILTIN_FALLBACK_MAP: dict[str, str] = {
    "DISCONNECTED": "e_Sleeping.jpg",
    "IDLE": "e_DefaultContent.jpg",
    "RECORDING": "e_Surprise.jpg",
    "PROCESSING": "e_Contempt.jpg",
    "PLAYING": "e_Joy.jpg",
    "LISTENING": "e_Surprise.jpg",
    "MOVING": "e_Joy2.jpg",
    "REARMING": "e_DefaultContent.jpg",
    "REBOOTING": "e_Sleepy.jpg",
    "CHARGING": "e_DefaultContent.jpg",
    "ERROR": "e_Sadness.jpg",
}

# Built-in fallback for the emotion-driven talking states, keyed by emotion.
BUILTIN_EMOTION_FALLBACK: dict[str, str] = {
    "neutral": "e_DefaultContent.jpg",
    "happy": "e_Joy.jpg",
    "excited": "e_Joy2.jpg",
    "sad": "e_Sadness.jpg",
    "curious": "e_Surprise.jpg",
}

# Direct map from each custom face asset filename to the built-in firmware face
# (e_*.jpg) used when custom assets are unavailable on the device. Every custom
# asset that a controller might display directly must appear here so the resolver
# can always degrade to a face that ships with the firmware (never a missing
# file). Keyed by the custom asset filename.
ASSET_BUILTIN_FALLBACK: dict[str, str] = {
    "face_idle.gif": "e_DefaultContent.jpg",
    "face_listening.png": "e_Surprise.jpg",
    "face_processing.gif": "e_Contempt.jpg",
    "face_talking_neutral.gif": "e_DefaultContent.jpg",
    "face_talking_happy.gif": "e_Joy.jpg",
    "face_talking_excited.gif": "e_Joy2.jpg",
    "face_talking_sad.gif": "e_Sadness.jpg",
    "face_talking_curious.gif": "e_Surprise.jpg",
}
# Built-in face shown when an unknown custom asset is requested.
DEFAULT_BUILTIN_FALLBACK = "e_DefaultContent.jpg"


def builtin_fallback_for_asset(filename: str) -> str:
    """Return the built-in firmware face to use in place of a custom asset.

    Built-in ``e_*.jpg`` faces ship with every Misty II, so they never fail on a
    missing file. Custom assets already keyed on their built-in map pass through
    that mapping; anything else degrades to the default content face.
    """
    if not filename:
        return DEFAULT_BUILTIN_FALLBACK
    if not filename.startswith("face_"):
        # Already a built-in / non-custom asset — display as-is.
        return filename
    return ASSET_BUILTIN_FALLBACK.get(filename, DEFAULT_BUILTIN_FALLBACK)


class FaceAnimator:
    """Companion-side face animation driver for Misty II.

    Runs a single daemon thread that pushes display frames to Misty via REST.
    The controller interacts only through set_state() (non-blocking) and
    stop() (bounded join). The animator never touches audio, LED, motors,
    or keyphrase endpoints.

    Args:
        misty_base_url: Base URL for Misty REST API (e.g., "http://10.0.0.23").
        enabled: If False, set_state() pushes static_fallback only (no looping).
        max_fps: Upper bound on animation FPS (from hardware validation).
        min_interval_s: Minimum seconds between REST frame pushes (rate limit).
        animation_map: State-to-AnimationSpec mapping. Defaults to single-frame.
    """

    STOP_TIMEOUT_S = 3.0  # max seconds to wait for thread join on stop()

    def __init__(
        self,
        misty_base_url: str,
        enabled: bool = False,
        max_fps: float = 4.0,
        min_interval_s: float = 0.25,
        animation_map: Optional[dict[str, AnimationSpec]] = None,
    ):
        self._base_url = misty_base_url.rstrip("/")
        self._enabled = enabled
        self._max_fps = max_fps
        self._min_interval_s = min_interval_s
        self._animation_map = animation_map or DEFAULT_ANIMATION_MAP

        self._lock = threading.Lock()
        self._state_changed = threading.Event()
        self._target_state: Optional[str] = None
        self._running = False
        self._thread: Optional[threading.Thread] = None
        self._last_displayed: Optional[str] = None

        # Emotion-aware talking faces (#110). The current emotion selects which
        # face_talking_{emotion}.gif is shown during emotion-driven states.
        self._emotion: str = DEFAULT_EMOTION
        # When custom face assets are unavailable on the device, fall back to
        # built-in firmware faces so display never fails on a missing file.
        self._custom_faces_available: bool = True

    @property
    def enabled(self) -> bool:
        return self._enabled

    @property
    def is_running(self) -> bool:
        return self._running and self._thread is not None and self._thread.is_alive()

    @property
    def emotion(self) -> str:
        """The current emotion used to select emotion-driven talking faces."""
        with self._lock:
            return self._emotion

    @property
    def custom_faces_available(self) -> bool:
        with self._lock:
            return self._custom_faces_available

    def set_custom_faces_available(self, available: bool) -> None:
        """Declare whether custom face assets are present on the device.

        When False, the animator resolves frames to built-in firmware faces
        (e_*.jpg) instead of the custom face_* assets. Typically set once at
        startup after the controller verifies/uploads the custom assets. If the
        availability changes while a frame is being shown, the current frame is
        refreshed so the display reflects the new source immediately.
        """
        with self._lock:
            if self._custom_faces_available == bool(available):
                return  # no change
            self._custom_faces_available = bool(available)
            active_state = self._target_state

        if active_state is None:
            return  # nothing displayed yet

        if not self._enabled:
            frame = self._resolve_single_frame(active_state)
            if frame:
                self._push_frame(frame)
            return

        self._state_changed.set()

    def resolve_asset(self, filename: str) -> str:
        """Resolve a custom face asset filename to the frame to actually display.

        When custom face assets are unavailable on the device, the built-in
        firmware fallback (``e_*.jpg``) is substituted so a display never fails
        on a missing file. Otherwise the custom asset is returned unchanged.
        Never raises.
        """
        with self._lock:
            custom_available = self._custom_faces_available
        if custom_available:
            return filename
        return builtin_fallback_for_asset(filename)

    def show_asset(self, filename: str) -> bool:
        """Display an arbitrary custom face asset immediately, with fallback.

        This is the single entry point for one-off / transient face displays
        (e.g., movement acknowledgment, error blips) that are not tied to a
        state transition. It applies built-in firmware fallback resolution but
        does **not** change the target animation state, so it will not disturb
        the state-driven animation loop. Best-effort; never raises.

        Deterministic display-failure fallback (#116): if a custom ``face_*``
        asset fails to display while custom faces were believed available, mark
        custom faces unavailable and immediately retry with the built-in
        firmware fallback so the display never gets stuck on a stale frame and
        subsequent calls resolve to built-ins.
        """
        frame = self.resolve_asset(filename)
        if self._push_frame(frame):
            return True

        with self._lock:
            was_available = self._custom_faces_available
        if was_available and isinstance(filename, str) and filename.startswith("face_"):
            self.set_custom_faces_available(False)
            return self._push_frame(builtin_fallback_for_asset(filename))
        return False

    def start(self):
        """Start the animation thread."""
        if self._thread is not None and self._thread.is_alive():
            return
        self._running = True
        self._thread = threading.Thread(
            target=self._animation_loop,
            name="FaceAnimator",
            daemon=True,
        )
        self._thread.start()
        logger.info(f"FaceAnimator started (enabled={self._enabled}, max_fps={self._max_fps})")

    def stop(self):
        """Stop the animation thread with bounded timeout."""
        self._running = False
        self._state_changed.set()  # wake the thread if sleeping
        if self._thread is not None and self._thread.is_alive():
            self._thread.join(timeout=self.STOP_TIMEOUT_S)
            if self._thread.is_alive():
                logger.warning("FaceAnimator thread did not stop within timeout")
        self._thread = None
        logger.info("FaceAnimator stopped")

    def set_emotion(self, emotion: str) -> None:
        """Set the current emotion for emotion-driven talking faces (#110).

        Non-blocking. If the animator is currently in an emotion-driven state
        (e.g., PLAYING), the displayed face refreshes to the new emotion.
        Unknown emotions are coerced to the neutral default.
        """
        e = (emotion or "").strip().lower()
        if e not in VALID_EMOTIONS:
            e = DEFAULT_EMOTION

        with self._lock:
            if self._emotion == e:
                return  # no change
            self._emotion = e
            active_state = self._target_state

        if active_state not in EMOTION_TALKING_STATES:
            return  # emotion only affects emotion-driven states

        if not self._enabled:
            frame = self._resolve_single_frame(active_state)
            if frame:
                self._push_frame(frame)
            return

        self._state_changed.set()

    def _resolve_single_frame(self, state_key: str) -> Optional[str]:
        """Resolve the single image filename to display for a state.

        Applies emotion selection for emotion-driven states and built-in
        firmware fallback when custom face assets are unavailable. Returns
        None if the state is unknown and has no fallback.
        """
        with self._lock:
            emotion = self._emotion
            custom_available = self._custom_faces_available

        if not custom_available:
            if state_key in EMOTION_TALKING_STATES:
                return BUILTIN_EMOTION_FALLBACK.get(
                    emotion, BUILTIN_EMOTION_FALLBACK[DEFAULT_EMOTION]
                )
            return BUILTIN_FALLBACK_MAP.get(state_key)

        if state_key in EMOTION_TALKING_STATES:
            return talking_face_for_emotion(emotion)

        spec = self._animation_map.get(state_key)
        if spec is None:
            return None
        # Prefer static_fallback per AnimationSpec's contract (the frame used
        # when animation is disabled/fails); fall back to frames[0] only when
        # no static_fallback is configured.
        if spec.static_fallback:
            return spec.static_fallback
        if spec.frames:
            return spec.frames[0]
        return None

    def set_state(self, state, emotion: Optional[str] = None) -> None:
        """Update the target animation state. Non-blocking.

        Args:
            state: A State enum value or string matching a key in animation_map.
            emotion: Optional emotion to apply before switching state. Used by
                emotion-driven states such as PLAYING to pick the matching
                talking face. Ignored (coerced to neutral) if not recognized.
        """
        # Accept both enum and string
        state_key = state.value if hasattr(state, "value") else str(state)

        # Apply emotion first so the frame resolved for this state reflects it.
        if emotion is not None:
            e = emotion.strip().lower() if isinstance(emotion, str) else DEFAULT_EMOTION
            if e not in VALID_EMOTIONS:
                e = DEFAULT_EMOTION
            with self._lock:
                self._emotion = e

        with self._lock:
            if self._target_state == state_key:
                same_state = True
            else:
                same_state = False
                self._target_state = state_key

        # Emotion-driven states may need a refresh even when the state is
        # unchanged (e.g., PLAYING with a new emotion). Non-emotion states
        # short-circuit on no-op transitions to preserve prior behavior.
        if same_state and state_key not in EMOTION_TALKING_STATES:
            return

        # If animation is disabled, push the resolved static frame immediately.
        if not self._enabled:
            frame = self._resolve_single_frame(state_key)
            if frame:
                self._push_frame(frame)
            return

        # Wake the animation thread to switch states
        self._state_changed.set()

    def _animation_loop(self):
        """Main animation thread loop."""
        current_state: Optional[str] = None
        frame_idx = 0

        while self._running:
            # Check for state change
            with self._lock:
                new_state = self._target_state

            if new_state != current_state:
                current_state = new_state
                frame_idx = 0
                self._state_changed.clear()

            if current_state is None:
                # No state set yet — wait for one
                self._state_changed.wait(timeout=1.0)
                continue

            spec = self._animation_map.get(current_state)
            if spec is None:
                # Unknown state — wait for next change
                self._state_changed.wait(timeout=1.0)
                continue

            # Single-frame: push once and wait for state change
            if spec.is_single_frame:
                frame = self._resolve_single_frame(current_state) or spec.frames[0]
                if self._last_displayed != frame:
                    self._push_frame(frame)
                self._state_changed.wait(timeout=5.0)
                self._state_changed.clear()
                continue

            # Multi-frame animation
            if frame_idx >= len(spec.frames):
                if spec.loop:
                    frame_idx = 0
                else:
                    # Hold last frame, wait for state change
                    self._state_changed.wait(timeout=5.0)
                    self._state_changed.clear()
                    continue

            frame = spec.frames[frame_idx]
            self._push_frame(frame)
            frame_idx += 1

            # Sleep for the frame interval (clamped to min_interval)
            clamped_fps = min(spec.fps, self._max_fps)
            interval = max(1.0 / clamped_fps, self._min_interval_s)

            # Interruptible sleep — wake on state change
            self._state_changed.wait(timeout=interval)
            if self._state_changed.is_set():
                self._state_changed.clear()

    def _push_frame(self, filename: str) -> bool:
        """Push a single display frame to Misty. Best-effort, never raises.

        Uses a short timeout and logs failures at debug level only.
        Returns True on success, False on failure.
        """
        if self._last_displayed == filename:
            return True  # already showing this frame

        url = f"{self._base_url}/api/images/display"
        try:
            resp = requests.post(
                url,
                json={"FileName": filename, "Alpha": 1},
                timeout=self._min_interval_s + 0.5,
            )
            if resp.status_code == 200:
                self._last_displayed = filename
                return True
            else:
                logger.debug(f"FaceAnimator frame push HTTP {resp.status_code}: {filename}")
                return False
        except Exception as e:
            logger.debug(f"FaceAnimator frame push failed: {filename} — {e}")
            return False
